apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ env.APP_NAME }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ env.APP_NAME }}
  template:
    metadata:
      labels:
        app: ${{ env.APP_NAME }}
        aadpodidbinding: ${{ env.APP_NAME }}
    spec:
      containers:
      - name: ${{ env.APP_NAME }}
        image: mdasandboxcontaineregistry.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        ports:
        - containerPort: 80