apiVersion: apps/v1
kind: Deployment
metadata:
  name: kordiaraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kordiaraw
  template:
    metadata:
      labels:
        app: kordiaraw
    spec:
      containers:
      - name: kordiaraw
        image: mdasandboxcontaineregistry.azurecr.io/kordiaraw:${{ github.event.head_commit.message }}
        ports:
        - containerPort: 80