apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: ${{ env.IDENTITY_NAME_LOWERCASE }}
spec:
  type: 0
  resourceID: ${{ secrets.IDENTITY_RESOURCE_ID }}
  clientID: ${{ secrets.IDENTITY_CLIENT_ID }}