on: [push]
env:
  REGISTRY_NAME: mdasandboxcontaineregistry
  CLUSTER_NAME: MDASandbox-kubecluster
  CLUSTER_RESOURCE_GROUP: MDASandbox-rg
  NAMESPACE: kordiaraw
  APP_NAME: kordiaraw
  SECRET: kordiaraw
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code changes
      uses: actions/checkout@main
    
    - name: Connect to Azure Container registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Container build and push to a Azure Container registry (ACR)
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
    
    - name: Set the target Azure Kubernetes Service (AKS) cluster. 
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    - name: Create namespace if doesn't exist
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
    - name: Create image pull secret for ACR
      uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: ${{ env.SECRET }}
        namespace: ${{ env.NAMESPACE }}

    - name: Ensure Identity Binding name is Lowercase
      env:
        AZURE_IDENTITY_NAME: ${{ secrets.AZURE_IDENTITY_NAME }}
      run: |
        echo "AZURE_IDENTITY_BIND_NAME=${AZURE_IDENTITY_NAME,,}" >>${GITHUB_ENV}

    - name: Secret Injector
      uses: Inrixia/Secret-Injector@v1
      with:
        secrets: ${{ toJson(secrets) }}
        env: ${{ toJson(env) }}
    
    - name: Deploy app to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/identity.yml
          manifests/identityBinding.yml
        images: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        imagepullsecrets: |
          ${{ env.SECRET }}
        namespace: ${{ env.NAMESPACE }}